const CountryOptions = [
  { label: "Morocco", value: "Morocco" },
  { label: "United Kingdom", value: "United Kingdom" },
  { label: "Iceland", value: "Iceland" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "Czech Republic", value: "Czech Republic" },
  { label: "France", value: "France" },
  { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "Jordan", value: "Jordan" },
  { label: "Greece", value: "Greece" },
  { label: "Lebanon", value: "Lebanon" },
  { label: "Egypt", value: "Egypt" },
  { label: "South Africa", value: "South Africa" },
  { label: "Finland", value: "Finland" },
  { label: "Belarus", value: "Belarus" },
  { label: "Namibia", value: "Namibia" },
  { label: "Iraq", value: "Iraq" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Russia", value: "Russia" },
  { label: "Kenya", value: "Kenya" },
  { label: "Georgia", value: "Georgia" },
  { label: "Iran", value: "Iran" },
  { label: "United Arab Emirates", value: "United Arab Emirates" },
  { label: "Azerbaijan", value: "Azerbaijan" },
  { label: "Mauritius", value: "Mauritius" },
  { label: "Armenia", value: "Armenia" },
  { label: "Afghanistan", value: "Afghanistan" },
  { label: "Pakistan", value: "Pakistan" },
  { label: "Uzbekistan", value: "Uzbekistan" },
  { label: "India", value: "India" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Nepal", value: "Nepal" },
  { label: "Kazakhstan", value: "Kazakhstan" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Myanmar", value: "Myanmar" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "China", value: "China" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Australia", value: "Australia" },
  { label: "Taiwan", value: "Taiwan" },
  { label: "Japan", value: "Japan" },
  { label: "South Korea", value: "South Korea" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Fiji", value: "Fiji" },
  { label: "Tonga", value: "Tonga" },
  { label: "Portugal", value: "Portugal" },
  { label: "Cape Verde", value: "Cape Verde" },
  { label: "Atlantic", value: "Atlantic" },
  { label: "Brazil", value: "Brazil" },
  { label: "Argentina", value: "Argentina" },
  { label: "Guyana", value: "Guyana" },
  { label: "Greenland", value: "Greenland" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Canada", value: "Canada" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Chile", value: "Chile" },
  { label: "Venezuela", value: "Venezuela" },
  { label: "Colombia", value: "Colombia" },
  { label: "United States", value: "United States" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "Mexico", value: "Mexico" },
  { label: "Samoa", value: "Samoa" },
  { label: "International", value: "International" },
];

// time zones -------------------------------------------------------------------------------
const TimezoneOptions = [
  { value: "Morocco Standard Time", label: "(GMT) Casablanca" },
  {
    value: "GMT Standard Time",
    label: "(GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London",
  },
  { value: "Greenwich Standard Time", label: "(GMT) Monrovia, Reykjavik" },
  {
    value: "W. Europe Standard Time",
    label: "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  },
  {
    value: "Central Europe Standard Time",
    label: "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  },
  {
    value: "Romance Standard Time",
    label: "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris",
  },
  {
    value: "Central European Standard Time",
    label: "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
  },
  {
    value: "W. Central Africa Standard Time",
    label: "(GMT+01:00) West Central Africa",
  },
  { value: "Jordan Standard Time", label: "(GMT+02:00) Amman" },
  {
    value: "GTB Standard Time",
    label: "(GMT+02:00) Athens, Bucharest, Istanbul",
  },
  { value: "Middle East Standard Time", label: "(GMT+02:00) Beirut" },
  { value: "Egypt Standard Time", label: "(GMT+02:00) Cairo" },
  {
    value: "South Africa Standard Time",
    label: "(GMT+02:00) Harare, Pretoria",
  },
  {
    value: "FLE Standard Time",
    label: "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
  },
  { value: "Israel Standard Time", label: "(GMT+02:00) Jerusalem" },
  { value: "E. Europe Standard Time", label: "(GMT+02:00) Minsk" },
  { value: "Namibia Standard Time", label: "(GMT+02:00) Windhoek" },
  { value: "Arabic Standard Time", label: "(GMT+03:00) Baghdad" },
  { value: "Arab Standard Time", label: "(GMT+03:00) Kuwait, Riyadh" },
  {
    value: "Russian Standard Time",
    label: "(GMT+03:00) Moscow, St. Petersburg, Volgograd",
  },
  { value: "E. Africa Standard Time", label: "(GMT+03:00) Nairobi" },
  { value: "Georgian Standard Time", label: "(GMT+03:00) Tbilisi" },
  { value: "Iran Standard Time", label: "(GMT+03:30) Tehran" },
  { value: "Arabian Standard Time", label: "(GMT+04:00) Abu Dhabi, Muscat" },
  { value: "Azerbaijan Standard Time", label: "(GMT+04:00) Baku" },
  { value: "Mauritius Standard Time", label: "(GMT+04:00) Port Louis" },
  { value: "Caucasus Standard Time", label: "(GMT+04:00) Yerevan" },
  { value: "Afghanistan Standard Time", label: "(GMT+04:30) Kabul" },
  { value: "Ekaterinburg Standard Time", label: "(GMT+05:00) Ekaterinburg" },
  { value: "Pakistan Standard Time", label: "(GMT+05:00) Islamabad, Karachi" },
  { value: "West Asia Standard Time", label: "(GMT+05:00) Tashkent" },
  {
    value: "India Standard Time",
    label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
  },
  {
    value: "Sri Lanka Standard Time",
    label: "(GMT+05:30) Sri Jayawardenepura",
  },
  { value: "Nepal Standard Time", label: "(GMT+05:45) Kathmandu" },
  {
    value: "N. Central Asia Standard Time",
    label: "(GMT+06:00) Almaty, Novosibirsk",
  },
  { value: "Central Asia Standard Time", label: "(GMT+06:00) Astana, Dhaka" },
  { value: "Myanmar Standard Time", label: "(GMT+06:30) Yangon (Rangoon)" },
  {
    value: "SE Asia Standard Time",
    label: "(GMT+07:00) Bangkok, Hanoi, Jakarta",
  },
  { value: "North Asia Standard Time", label: "(GMT+07:00) Krasnoyarsk" },
  {
    value: "China Standard Time",
    label: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
  },
  {
    value: "North Asia East Standard Time",
    label: "(GMT+08:00) Irkutsk, Ulaan Bataar",
  },
  {
    value: "Singapore Standard Time",
    label: "(GMT+08:00) Kuala Lumpur, Singapore",
  },
  { value: "W. Australia Standard Time", label: "(GMT+08:00) Perth" },
  { value: "Taipei Standard Time", label: "(GMT+08:00) Taipei" },
  { value: "Tokyo Standard Time", label: "(GMT+09:00) Osaka, Sapporo, Tokyo" },
  { value: "Korea Standard Time", label: "(GMT+09:00) Seoul" },
  { value: "Yakutsk Standard Time", label: "(GMT+09:00) Yakutsk" },
  { value: "Cen. Australia Standard Time", label: "(GMT+09:30) Adelaide" },
  { value: "AUS Central Standard Time", label: "(GMT+09:30) Darwin" },
  { value: "E. Australia Standard Time", label: "(GMT+10:00) Brisbane" },
  {
    value: "AUS Eastern Standard Time",
    label: "(GMT+10:00) Canberra, Melbourne, Sydney",
  },
  {
    value: "West Pacific Standard Time",
    label: "(GMT+10:00) Guam, Port Moresby",
  },
  { value: "Tasmania Standard Time", label: "(GMT+10:00) Hobart" },
  { value: "Vladivostok Standard Time", label: "(GMT+10:00) Vladivostok" },
  {
    value: "Central Pacific Standard Time",
    label: "(GMT+11:00) Magadan, Solomon Is., New Caledonia",
  },
  {
    value: "New Zealand Standard Time",
    label: "(GMT+12:00) Auckland, Wellington",
  },
  {
    value: "Fiji Standard Time",
    label: "(GMT+12:00) Fiji, Kamchatka, Marshall Is.",
  },
  { value: "Tonga Standard Time", label: "(GMT+13:00) Nuku'alofa" },
  { value: "Azores Standard Time", label: "(GMT-01:00) Azores" },
  { value: "Cape Verde Standard Time", label: "(GMT-01:00) Cape Verde Is." },
  { value: "Mid-Atlantic Standard Time", label: "(GMT-02:00) Mid-Atlantic" },
  { value: "E. South America Standard Time", label: "(GMT-03:00) Brasilia" },
  { value: "Argentina Standard Time", label: "(GMT-03:00) Buenos Aires" },
  { value: "SA Eastern Standard Time", label: "(GMT-03:00) Georgetown" },
  { value: "Greenland Standard Time", label: "(GMT-03:00) Greenland" },
  { value: "Montevideo Standard Time", label: "(GMT-03:00) Montevideo" },
  { value: "Newfoundland Standard Time", label: "(GMT-03:30) Newfoundland" },
  {
    value: "Atlantic Standard Time",
    label: "(GMT-04:00) Atlantic Time (Canada)",
  },
  { value: "SA Western Standard Time", label: "(GMT-04:00) La Paz" },
  { value: "Central Brazilian Standard Time", label: "(GMT-04:00) Manaus" },
  { value: "Pacific SA Standard Time", label: "(GMT-04:00) Santiago" },
  { value: "Venezuela Standard Time", label: "(GMT-04:30) Caracas" },
  {
    value: "SA Pacific Standard Time",
    label: "(GMT-05:00) Bogota, Lima, Quito, Rio Branco",
  },
  {
    value: "Eastern Standard Time",
    label: "(GMT-05:00) Eastern Time (US & Canada)",
  },
  { value: "US Eastern Standard Time", label: "(GMT-05:00) Indiana (East)" },
  {
    value: "Central America Standard Time",
    label: "(GMT-06:00) Central America",
  },
  {
    value: "Central Standard Time",
    label: "(GMT-06:00) Central Time (US & Canada)",
  },
  {
    value: "Central Standard Time (Mexico)",
    label: "(GMT-06:00) Guadalajara, Mexico City, Monterrey",
  },
  { value: "Canada Central Standard Time", label: "(GMT-06:00) Saskatchewan" },
  { value: "US Mountain Standard Time", label: "(GMT-07:00) Arizona" },
  {
    value: "Mountain Standard Time (Mexico)",
    label: "(GMT-07:00) Chihuahua, La Paz, Mazatlan",
  },
  {
    value: "Mountain Standard Time",
    label: "(GMT-07:00) Mountain Time (US & Canada)",
  },
  {
    value: "Pacific Standard Time",
    label: "(GMT-08:00) Pacific Time (US & Canada)",
  },
  {
    value: "Pacific Standard Time (Mexico)",
    label: "(GMT-08:00) Tijuana, Baja California",
  },
  { value: "Alaskan Standard Time", label: "(GMT-09:00) Alaska" },
  { value: "Hawaiian Standard Time", label: "(GMT-10:00) Hawaii" },
  { value: "Samoa Standard Time", label: "(GMT-11:00) Midway Island, Samoa" },
  {
    value: "Dateline Standard Time",
    label: "(GMT-12:00) International Date Line West",
  },
];

const PreferredDays = [
  { value: "Monday", label: "Monday" },
  { value: "Tuesday", label: "Tuesday" },
  { value: "Wednesday", label: "Wednesday" },
  { value: "Thursday", label: "Thursday" },
  { value: "Friday", label: "Friday" },
  { value: "Saturday", label: "Saturday" },
  { value: "Sunday", label: "Sunday" },
];

const PreferredTimes = [
  { value: "1am", label: "1am" },
  { value: "2am", label: "2am" },
  { value: "3am", label: "3am" },
  { value: "4am", label: "4am" },
  { value: "5am", label: "5am" },
  { value: "6am", label: "6am" },
  { value: "7am", label: "7am" },
  { value: "8am", label: "8am" },
  { value: "9am", label: "9am" },
  { value: "10am", label: "10am" },
  { value: "11am", label: "11am" },
  { value: "12am", label: "12am" },
  { value: "1pm", label: "1pm" },
  { value: "2pm", label: "2pm" },
  { value: "3pm", label: "3pm" },
  { value: "4pm", label: "4pm" },
  { value: "5pm", label: "5pm" },
  { value: "6pm", label: "6pm" },
  { value: "7pm", label: "7pm" },
  { value: "8pm", label: "8pm" },
  { value: "9pm", label: "9pm" },
  { value: "10pm", label: "10pm" },
  { value: "11pm", label: "11pm" },
  { value: "12pm", label: "12pm" },
];





export { TimezoneOptions, CountryOptions, PreferredDays, PreferredTimes };
